import '../utilitis/common_import.dart';

class LanguagesTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    "en": {
      "Start_Calling": "Start Calling",
      "Skip": "Skip",
      "OnBoardingText1": "Join Meeting anywhere, any time.",
      "OnBoardingText2": "Sign in to see all of you upcoming meetings or to schedule a new meeting.",
      "OnBoardingText3": "Connect  with your team",
      "Next": "Next",
      "Done": "Done",
      "Secure": "Secure, Smart, and Streamline Conversations",
      "Join_Meeting": "Join Meeting",
      "Sign_In": "Sign In",
      "Sign_in": "Sign in",
      "Don’t_account": "Don’t have an account? ",
      "Already_have_account": "Already have an account? ",
      "Sign_Up": "Sign Up",
      "Sign_up": "Sign up",
      "Cancel": "Cancel",
      "Enter_your_email": "Enter your email address",
      "Email": "Email",
      "Password": "Password",
      "Required": "Required",
      "Forgot_password": "Forgot password?",
      "Forgot_Password": "Forgot Password",
      "Other_Method": "Other Sign in Method",
      "Other_sign_up_Method": "Other Sign up Method",
      "Sign_in_Apple": "Sign in with Apple",
      "Sign_in_Google": "Sign in with Google",
      "Reset_password_text": "To reset your password, Please enter your email address.",
      "Send": "Send",
      "Forgot_Password_Dialog_Text":
          "We just sent an email to user@exaple.com with a link to reset your password. Check your inbox and follow the instructions in the email.",
      "OK": "Ok",
      "Check_your_email": "Check your email",
      "Verification_code_text": "We sent a verification code to user@example.com",
      "Code": "Code",
      "Verification_Code": "Verification Code",
      "Didn’t_receive_verification_code": "Didn’t receive a verification code?",
      "Resend": "Resend",
      "Welcome_to_Weboxcam": "Welcome to Weboxcam",
      "Set_up_display_name_text": "Let’s set up your display name in Weboxcam and create a password.",
      "First_Name": "First Name",
      "Last_Name": "Last Name",
      "Enter_First_Name": "Enter First Name",
      "Enter_Last_Name": "Enter Last Name",
      "Password_Requirements": "Password Requirements*",
      "Must_Contain": "Must Contain",
      "At_least_number": "•  At least 1 number",
      "At_least_Uppercase": "•  At least 1 Uppercase letter",
      "At_least_lowercase": "•  At least 1 lowercase letter",
      "At_least_8": "•  At least 8 characters",
      "Confirm_sign_up": "Confirm sign up",
      "Get_Notified": "Get Notified",
      "Enable_notifications_text": "Enable notifications to receive alerts for message meetings and offers. You can manage these in app settings.",
      "Enable_notifications": "Enable Notification",
      "Not_Now": "Not Now",
      "Never_Miss_a_meetings": "Never Miss a meetings",
      "Allow_Weboxcam_to_access_your":
          "Allow Weboxcam to access your calendar so you can easily schedule meetings and join upcoming meetings directly from the app.",
      "Continue": "Continue",
      "You’re_ready": "You’re ready to go!",
      "Welcome_to_Weboxcam_for_Team_chat": "Welcome to Weboxcam one app for Team chat, phone, meeting and more.",
      "Go_To_Home": "Go To Home",
      "Meeting": "Meeting",
      "Schedule": "Schedule",
      "Message": "Message",
      "Setting": "Setting",
      "Settings": "Settings",
      "Calendar": "Calendar",
      "Start_New_Meeting": "Start New Meeting",
      "Schedule_Meeting": "Schedule Meeting",
      "No_Any_Meeting": "No Any Meeting",
      "No_Any_Schedule": "No Any Schedule",
      "No_Any_Message": "No Any Message",
      "On_Going": "On Going",
      "Meeting_ID": "Meeting ID:",
      "Join_Now": "Join Now",
      "Set_Status": "Set Status",
      "Online": "Online",
      "Offline": "Offline",
      "Available": "Available",
      "Away": "Away",
      "Busy": "Busy",
      "Out_of_Office": "Out of Office",
      "Notification_Preference": "Notification Preference",
      "Languages": "Languages",
      "Theme": "Theme",
      "About_Us": "About Us",
      "Terms_Policy": "Terms & Policy",
      "Rate_App": "Rate App",
      "Share_App": "Share App",
      "Help_Support": "Help & Support",
      "Logout": "Logout",
      "Log_Out": "Log Out",
      "Log_out_dialog_text": "Are you sure want to log out?",
      "Start_meeting": "Start a meeting",
      "Video_Connect": "Video Connect",
      "Use_Personal_ID": "Use Personal Meeting ID",
      "Join_meeting": "Join meeting",
      "Meeting_Id": "Meeting ID",
      "Personal_Link": "Personal Link",
      "Join_with_personal_link": "Join with a personal link",
      "Join_with_meeting_ID": "Join with meeting ID",
      "Enter_the_URL": "If you are invited to a personal room, you can enter the URL",
      "Add_Name": "Add Name",
      "Join": "Join",
      "Invitation_link": "If you received an invitation link, tap on the link again to join the meeting.",
      "Join_Option": "Join Option",
      "Connect_to_audio": "Connect to audio",
      "Don’t_Connect_to_audio": "Don’t Connect to audio",
      "Turn_on_my_video": "Turn on my video",
      "Turn_off_my_video": "Turn off my video",
      "Meeting_Name": "Meeting Name",
      "Date": "Date",
      "Time": "Time",
      "Time_Zone": "Time Zone",
      "Duration": "Duration",
      "Security": "Security",
      "Passcode": "Passcode",
      "Meeting_Options": "Meeting Options",
      "Host_video": "Host video",
      "Host_Audio": "Host Audio",
      "Edit": "Edit",
      "Remove_Scheduled_Meeting": "Remove Scheduled Meeting",
      "Delete_scheduled_meeting_dialog_text": "Are you sure you want to delete the scheduled meeting?",
      "Remove": "Remove",
      "Delete": "Delete",
      "Passcode:": "Passcode:",
      "Link:": "Link:",
      "Members": "Members",
      "Show_More": "Show More",
      "Invite_To_mail": "Invite To mail",
      "Invite": "Invite",
      "Chat": "Chat",
      "Start": "Start",
      "Owner": "Owner",
      "Clear_All": "Clear All",
      "Write_your_message": "Write your message",
      "My_Profile": "My Profile",
      "Display_Name": "Display Name",
      "Phone_Number": "Phone Number",
      "Location": "Location",
      "Job_Title": "Job Title",
      "Job_Titles": "Job Titles",
      "Update_Password": "Update Password",
      "Not_Set": "Not Set",
      "Update": "Update",
      "Enter your mobile number": "Enter your mobile number",
      "Search_Location": "Search Location",
      "Save": "Save",
      "Your_Designation": "Your Designation",
      "Current_Password": "Current Password",
      "Enter_Old_Password": "Enter Old Password",
      "New_Password": "New Password",
      "Enter_New_Password": "Enter New Password",
      "Confirm_Password": "Confirm Password",
      "Confirm_New_Password": "Confirm Your New Password",
      "Notification": "Notification",
      "Notification_text": "You can enable or disable all notifications to suit your preferences easily.",
      "Light": "Light",
      "Dark": "Dark",
      "System_Default": "System Default",
    },
    "es": {
      "Start_Calling": "Iniciar llamada",
      "Skip": "Omitir",
      "OnBoardingText1": "Únete a una reunión desde cualquier lugar, en cualquier momento.",
      "OnBoardingText2": "Inicia sesión para ver todas tus próximas reuniones o para programar una nueva.",
      "OnBoardingText3": "Conéctate con tu equipo",
      "Next": "Siguiente",
      "Done": "Hecho",
      "Secure": "Conversaciones seguras, inteligentes y eficientes",
      "Join_Meeting": "Unirse a la reunión",
      "Sign_In": "Iniciar sesión",
      "Sign_in": "Iniciar sesión",
      "Don’t_account": "¿No tienes cuenta? ",
      "Already_have_account": "¿Ya tienes una cuenta? ",
      "Sign_Up": "Registrarse",
      "Sign_up": "Regístrate",
      "Cancel": "Cancelar",
      "Enter_your_email": "Introduce tu dirección de correo electrónico",
      "Email": "Correo electrónico",
      "Password": "Contraseña",
      "Required": "Requerido",
      "Forgot_password": "¿Olvidaste tu contraseña?",
      "Forgot_Password": "Olvidaste la contraseña",
      "Other_Method": "Otro método de inicio de sesión",
      "Other_sign_up_Method": "Otro método de registro",
      "Sign_in_Apple": "Iniciar sesión con Apple",
      "Sign_in_Google": "Iniciar sesión con Google",
      "Reset_password_text": "Para restablecer tu contraseña, ingresa tu dirección de correo electrónico.",
      "Send": "Enviar",
      "Forgot_Password_Dialog_Text":
          "Acabamos de enviar un correo a user@exaple.com con un enlace para restablecer tu contraseña. Revisa tu bandeja y sigue las instrucciones.",
      "OK": "Ok",
      "Check_your_email": "Revisa tu correo",
      "Verification_code_text": "Enviamos un código de verificación a user@example.com",
      "Code": "Código",
      "Verification_Code": "Código de verificación",
      "Didn’t_receive_verification_code": "¿No recibiste el código de verificación?",
      "Resend": "Reenviar",
      "Welcome_to_Weboxcam": "Bienvenido a Weboxcam",
      "Set_up_display_name_text": "Configura tu nombre visible en Weboxcam y crea una contraseña.",
      "First_Name": "Nombre",
      "Last_Name": "Apellido",
      "Enter_First_Name": "Ingresa el nombre",
      "Enter_Last_Name": "Ingresa el apellido",
      "Password_Requirements": "Requisitos de contraseña*",
      "Must_Contain": "Debe contener",
      "At_least_number": "• Al menos 1 número",
      "At_least_Uppercase": "• Al menos 1 letra mayúscula",
      "At_least_lowercase": "• Al menos 1 letra minúscula",
      "At_least_8": "• Al menos 8 caracteres",
      "Confirm_sign_up": "Confirmar registro",
      "Get_Notified": "Recibir notificaciones",
      "Enable_notifications_text":
          "Activa las notificaciones para recibir alertas sobre mensajes, reuniones y ofertas. Puedes gestionarlas en la configuración de la app.",
      "Enable_notifications": "Habilitar notificaciones",
      "Not_Now": "Ahora no",
      "Never_Miss_a_meetings": "No pierdas ninguna reunión",
      "Allow_Weboxcam_to_access_your": "Permite que Weboxcam acceda a tu calendario para programar y unirte a reuniones directamente desde la app.",
      "Continue": "Continuar",
      "You’re_ready": "¡Estás listo!",
      "Welcome_to_Weboxcam_for_Team_chat": "Bienvenido a Weboxcam: una app para chat en equipo, llamada, reunión y más.",
      "Go_To_Home": "Ir al inicio",
      "Meeting": "Reunión",
      "Schedule": "Programar",
      "Message": "Mensaje",
      "Setting": "Configuración",
      "Settings": "Configuración",
      "Calendar": "Calendario",
      "Start_New_Meeting": "Iniciar nueva reunión",
      "Schedule_Meeting": "Programar reunión",
      "No_Any_Meeting": "No hay ninguna reunión",
      "No_Any_Schedule": "No hay eventos programados",
      "No_Any_Message": "No hay mensajes",
      "On_Going": "En curso",
      "Meeting_ID": "ID de reunión:",
      "Join_Now": "Unirse ahora",
      "Set_Status": "Establecer estado",
      "Online": "En línea",
      "Offline": "Desconectado",
      "Available": "Disponible",
      "Away": "Ausente",
      "Busy": "Ocupado",
      "Out_of_Office": "Fuera de la oficina",
      "Notification_Preference": "Preferencias de notificación",
      "Languages": "Idiomas",
      "Theme": "Tema",
      "About_Us": "Acerca de nosotros",
      "Terms_Policy": "Términos y políticas",
      "Rate_App": "Calificar app",
      "Share_App": "Compartir app",
      "Help_Support": "Ayuda y soporte",
      "Logout": "Cerrar sesión",
      "Log_Out": "Cerrar sesión",
      "Log_out_dialog_text": "¿Estás seguro de que deseas cerrar sesión?",
      "Start_meeting": "Iniciar una reunión",
      "Video_Connect": "Conexión de video",
      "Use_Personal_ID": "Usar ID personal de reunión",
      "Join_meeting": "Unirse a la reunión",
      "Meeting_Id": "ID de reunión",
      "Personal_Link": "Enlace personal",
      "Join_with_personal_link": "Unirse con enlace personal",
      "Join_with_meeting_ID": "Unirse con ID de reunión",
      "Enter_the_URL": "Si fuiste invitado a una sala personal, puedes ingresar la URL",
      "Add_Name": "Agregar nombre",
      "Join": "Unirse",
      "Invitation_link": "Si recibiste un enlace de invitación, tócalo nuevamente para unirte a la reunión.",
      "Join_Option": "Opción de unirse",
      "Connect_to_audio": "Conectar al audio",
      "Don’t_Connect_to_audio": "No conectar al audio",
      "Turn_on_my_video": "Encender mi video",
      "Turn_off_my_video": "Apagar mi video",
      "Meeting_Name": "Nombre de la reunión",
      "Date": "Fecha",
      "Time": "Hora",
      "Time_Zone": "Zona horaria",
      "Duration": "Duración",
      "Security": "Seguridad",
      "Passcode": "Código de acceso",
      "Meeting_Options": "Opciones de reunión",
      "Host_video": "Video del anfitrión",
      "Host_Audio": "Audio del anfitrión",
      "Edit": "Editar",
      "Remove_Scheduled_Meeting": "Eliminar reunión programada",
      "Delete_scheduled_meeting_dialog_text": "¿Seguro que quieres eliminar la reunión programada?",
      "Remove": "Eliminar",
      "Delete": "Borrar",
      "Passcode:": "Código:",
      "Link:": "Enlace:",
      "Members": "Miembros",
      "Show_More": "Mostrar más",
      "Invite_To_mail": "Invitar por correo",
      "Invite": "Invitar",
      "Chat": "Chat",
      "Start": "Iniciar",
      "Owner": "Propietario",
      "Clear_All": "Borrar todo",
      "Write_your_message": "Escribe tu mensaje",
      "My_Profile": "Mi perfil",
      "Display_Name": "Nombre visible",
      "Phone_Number": "Número de teléfono",
      "Location": "Ubicación",
      "Job_Title": "Puesto",
      "Job_Titles": "Puestos",
      "Update_Password": "Actualizar contraseña",
      "Not_Set": "No establecido",
      "Update": "Actualizar",
      "Enter your mobile number": "Introduce tu número de móvil",
      "Search_Location": "Buscar ubicación",
      "Save": "Guardar",
      "Your_Designation": "Tu cargo",
      "Current_Password": "Contraseña actual",
      "Enter_Old_Password": "Introduce la contraseña anterior",
      "New_Password": "Nueva contraseña",
      "Enter_New_Password": "Ingresa la nueva contraseña",
      "Confirm_Password": "Confirmar contraseña",
      "Confirm_New_Password": "Confirma tu nueva contraseña",
      "Notification": "Notificación",
      "Notification_text": "Puedes activar o desactivar todas las notificaciones para ajustarlas fácilmente según tus preferencias.",
      "Light": "Claro",
      "Dark": "Oscuro",
      "System_Default": "Predeterminado del sistema",
    },
    "fr": {
      "Start_Calling": "Commencer l'appel",
      "Skip": "Passer",
      "OnBoardingText1": "Rejoignez des réunions partout, à tout moment.",
      "OnBoardingText2": "Connectez-vous pour voir toutes vos réunions à venir ou pour planifier une nouvelle réunion.",
      "OnBoardingText3": "Connectez-vous avec votre équipe",
      "Next": "Suivant",
      "Done": "Terminé",
      "Secure": "Des conversations sécurisées, intelligentes et efficaces",
      "Join_Meeting": "Rejoindre la réunion",
      "Sign_In": "Se connecter",
      "Sign_in": "Se connecter",
      "Don’t_account": "Vous n’avez pas de compte ? ",
      "Already_have_account": "Vous avez déjà un compte ? ",
      "Sign_Up": "S’inscrire",
      "Sign_up": "S’inscrire",
      "Cancel": "Annuler",
      "Enter_your_email": "Entrez votre adresse e-mail",
      "Email": "E-mail",
      "Password": "Mot de passe",
      "Required": "Obligatoire",
      "Forgot_password": "Mot de passe oublié ?",
      "Forgot_Password": "Mot de passe oublié",
      "Other_Method": "Autre méthode de connexion",
      "Other_sign_up_Method": "Autre méthode d’inscription",
      "Sign_in_Apple": "Se connecter avec Apple",
      "Sign_in_Google": "Se connecter avec Google",
      "Reset_password_text": "Pour réinitialiser votre mot de passe, veuillez entrer votre adresse e-mail.",
      "Send": "Envoyer",
      "Forgot_Password_Dialog_Text":
          "Nous avons envoyé un e-mail à user@exaple.com avec un lien pour réinitialiser votre mot de passe. Vérifiez votre boîte de réception et suivez les instructions.",
      "OK": "Ok",
      "Check_your_email": "Vérifiez votre e-mail",
      "Verification_code_text": "Nous avons envoyé un code de vérification à user@example.com",
      "Code": "Code",
      "Verification_Code": "Code de vérification",
      "Didn’t_receive_verification_code": "Vous n’avez pas reçu de code de vérification ?",
      "Resend": "Renvoyer",
      "Welcome_to_Weboxcam": "Bienvenue sur Weboxcam",
      "Set_up_display_name_text": "Configurons votre nom d’affichage sur Weboxcam et créons un mot de passe.",
      "First_Name": "Prénom",
      "Last_Name": "Nom",
      "Enter_First_Name": "Entrez le prénom",
      "Enter_Last_Name": "Entrez le nom",
      "Password_Requirements": "Exigences du mot de passe*",
      "Must_Contain": "Doit contenir",
      "At_least_number": "•  Au moins 1 chiffre",
      "At_least_Uppercase": "•  Au moins 1 lettre majuscule",
      "At_least_lowercase": "•  Au moins 1 lettre minuscule",
      "At_least_8": "•  Au moins 8 caractères",
      "Confirm_sign_up": "Confirmer l’inscription",
      "Get_Notified": "Recevoir des notifications",
      "Enable_notifications_text":
          "Activez les notifications pour recevoir des alertes de messages, de réunions et d’offres. Vous pouvez les gérer dans les paramètres.",
      "Enable_notifications": "Activer les notifications",
      "Not_Now": "Pas maintenant",
      "Never_Miss_a_meetings": "Ne manquez jamais une réunion",
      "Allow_Weboxcam_to_access_your":
          "Autorisez Weboxcam à accéder à votre calendrier pour planifier et rejoindre facilement vos réunions directement depuis l’application.",
      "Continue": "Continuer",
      "You’re_ready": "Vous êtes prêt !",
      "Welcome_to_Weboxcam_for_Team_chat": "Bienvenue sur Weboxcam, une application pour discuter, appeler, organiser des réunions et plus encore.",
      "Go_To_Home": "Aller à l’accueil",
      "Meeting": "Réunion",
      "Schedule": "Planifier",
      "Message": "Message",
      "Setting": "Paramètres",
      "Settings": "Paramètres",
      "Calendar": "Calendrier",
      "Start_New_Meeting": "Démarrer une nouvelle réunion",
      "Schedule_Meeting": "Planifier une réunion",
      "No_Any_Meeting": "Aucune réunion",
      "No_Any_Schedule": "Aucun horaire",
      "No_Any_Message": "Aucun message",
      "On_Going": "En cours",
      "Meeting_ID": "ID de la réunion :",
      "Join_Now": "Rejoindre maintenant",
      "Set_Status": "Définir le statut",
      "Online": "En ligne",
      "Offline": "Hors ligne",
      "Available": "Disponible",
      "Away": "Absent",
      "Busy": "Occupé",
      "Out_of_Office": "Hors du bureau",
      "Notification_Preference": "Préférences de notification",
      "Languages": "Langues",
      "Theme": "Thème",
      "About_Us": "À propos de nous",
      "Terms_Policy": "Conditions & Politique",
      "Rate_App": "Noter l’application",
      "Share_App": "Partager l’application",
      "Help_Support": "Aide & Support",
      "Logout": "Déconnexion",
      "Log_Out": "Déconnexion",
      "Log_out_dialog_text": "Êtes-vous sûr de vouloir vous déconnecter ?",
      "Start_meeting": "Démarrer une réunion",
      "Video_Connect": "Connexion vidéo",
      "Use_Personal_ID": "Utiliser l’ID personnel de réunion",
      "Join_meeting": "Rejoindre la réunion",
      "Meeting_Id": "ID de la réunion",
      "Personal_Link": "Lien personnel",
      "Join_with_personal_link": "Rejoindre avec un lien personnel",
      "Join_with_meeting_ID": "Rejoindre avec l’ID de la réunion",
      "Enter_the_URL": "Si vous êtes invité à une salle personnelle, entrez l’URL",
      "Add_Name": "Ajouter un nom",
      "Join": "Rejoindre",
      "Invitation_link": "Si vous avez reçu un lien d’invitation, cliquez dessus pour rejoindre la réunion.",
      "Join_Option": "Option de participation",
      "Connect_to_audio": "Se connecter à l’audio",
      "Don’t_Connect_to_audio": "Ne pas se connecter à l’audio",
      "Turn_on_my_video": "Activer ma vidéo",
      "Turn_off_my_video": "Désactiver ma vidéo",
      "Meeting_Name": "Nom de la réunion",
      "Date": "Date",
      "Time": "Heure",
      "Time_Zone": "Fuseau horaire",
      "Duration": "Durée",
      "Security": "Sécurité",
      "Passcode": "Code d’accès",
      "Meeting_Options": "Options de réunion",
      "Host_video": "Vidéo de l’hôte",
      "Host_Audio": "Audio de l’hôte",
      "Edit": "Modifier",
      "Remove_Scheduled_Meeting": "Supprimer la réunion planifiée",
      "Delete_scheduled_meeting_dialog_text": "Êtes-vous sûr de vouloir supprimer la réunion planifiée ?",
      "Remove": "Supprimer",
      "Delete": "Supprimer",
      "Passcode:": "Code d’accès :",
      "Link:": "Lien :",
      "Members": "Membres",
      "Show_More": "Afficher plus",
      "Invite_To_mail": "Inviter par e-mail",
      "Invite": "Inviter",
      "Chat": "Chat",
      "Start": "Démarrer",
      "Owner": "Propriétaire",
      "Clear_All": "Tout effacer",
      "Write_your_message": "Écrivez votre message",
      "My_Profile": "Mon profil",
      "Display_Name": "Nom d’affichage",
      "Phone_Number": "Numéro de téléphone",
      "Location": "Lieu",
      "Job_Title": "Poste",
      "Job_Titles": "Postes",
      "Update_Password": "Mettre à jour le mot de passe",
      "Not_Set": "Non défini",
      "Update": "Mettre à jour",
      "Enter your mobile number": "Entrez votre numéro de téléphone",
      "Search_Location": "Rechercher un lieu",
      "Save": "Enregistrer",
      "Your_Designation": "Votre poste",
      "Current_Password": "Mot de passe actuel",
      "Enter_Old_Password": "Entrez l’ancien mot de passe",
      "New_Password": "Nouveau mot de passe",
      "Enter_New_Password": "Entrez le nouveau mot de passe",
      "Confirm_Password": "Confirmer le mot de passe",
      "Confirm_New_Password": "Confirmez votre nouveau mot de passe",
      "Notification": "Notification",
      "Notification_text": "Vous pouvez activer ou désactiver toutes les notifications selon vos préférences.",
      "Light": "Clair",
      "Dark": "Sombre",
      "System_Default": "Par défaut du système",
    },
    "ko": {
      "Start_Calling": "통화 시작",
      "Skip": "건너뛰기",
      "OnBoardingText1": "언제 어디서나 회의에 참여하세요.",
      "OnBoardingText2": "로그인하여 예정된 모든 회의를 확인하거나 새 회의를 예약하세요.",
      "OnBoardingText3": "팀과 연결하기",
      "Next": "다음",
      "Done": "완료",
      "Secure": "안전하고 스마트하며 간편한 대화",
      "Join_Meeting": "회의 참여",
      "Sign_In": "로그인",
      "Sign_in": "로그인",
      "Don’t_account": "계정이 없으신가요? ",
      "Already_have_account": "이미 계정이 있으신가요? ",
      "Sign_Up": "회원 가입",
      "Sign_up": "회원 가입",
      "Cancel": "취소",
      "Enter_your_email": "이메일 주소 입력",
      "Email": "이메일",
      "Password": "비밀번호",
      "Required": "필수",
      "Forgot_password": "비밀번호를 잊으셨나요?",
      "Forgot_Password": "비밀번호 찾기",
      "Other_Method": "다른 로그인 방법",
      "Other_sign_up_Method": "다른 회원가입 방법",
      "Sign_in_Apple": "Apple로 로그인",
      "Sign_in_Google": "Google로 로그인",
      "Reset_password_text": "비밀번호를 재설정하려면 이메일 주소를 입력해 주세요.",
      "Send": "전송",
      "Forgot_Password_Dialog_Text": "reset@example.com 계정으로 비밀번호 재설성 링크를 보냈습니다. 받은 편지함을 확인하고 지침을 따르세요.",
      "OK": "확인",
      "Check_your_email": "이메일을 확인하세요",
      "Verification_code_text": "user@example.com로 인증 코드를 보냈습니다",
      "Code": "코드",
      "Verification_Code": "인증 코드",
      "Didn’t_receive_verification_code": "인증 코드를 못 받으셨나요?",
      "Resend": "재전송",
      "Welcome_to_Weboxcam": "Weboxcam에 오신 것을 환영합니다",
      "Set_up_display_name_text": "Weboxcam에서 사용할 표시 이름을 설정하고 비밀번호를 생성하세요.",
      "First_Name": "이름",
      "Last_Name": "성",
      "Enter_First_Name": "이름 입력",
      "Enter_Last_Name": "성 입력",
      "Password_Requirements": "비밀번호 요구 사항*",
      "Must_Contain": "다음을 포함해야 합니다",
      "At_least_number": "•  숫자 1개 이상",
      "At_least_Uppercase": "•  대문자 1개 이상",
      "At_least_lowercase": "•  소문자 1개 이상",
      "At_least_8": "•  8자 이상",
      "Confirm_sign_up": "회원가입 확인",
      "Get_Notified": "알림 받기",
      "Enable_notifications_text": "메시지, 회의 및 혜택 알림을 받도록 알림을 활성화하세요. 앱 설정에서 관리할 수 있습니다.",
      "Enable_notifications": "알림 활성화",
      "Not_Now": "나중에",
      "Never_Miss_a_meetings": "회의를 놓치지 마세요",
      "Allow_Weboxcam_to_access_your": "Weboxcam이 캘린더에 접근하도록 허용하면, 앱에서 간편하게 회의를 예약하고 참여할 수 있습니다.",
      "Continue": "계속",
      "You’re_ready": "준비가 완료되었습니다!",
      "Welcome_to_Weboxcam_for_Team_chat": "Weboxcam에 오신 것을 환영합니다 – 팀 채팅, 전화, 회의를 하나의 앱에서.",
      "Go_To_Home": "홈으로 이동",
      "Meeting": "회의",
      "Schedule": "일정",
      "Message": "메시지",
      "Setting": "설정",
      "Settings": "설정",
      "Calendar": "캘린더",
      "Start_New_Meeting": "새 회의 시작",
      "Schedule_Meeting": "회의 예약",
      "No_Any_Meeting": "회의가 없습니다",
      "No_Any_Schedule": "일정이 없습니다",
      "No_Any_Message": "메시지가 없습니다",
      "On_Going": "진행 중",
      "Meeting_ID": "회의 ID:",
      "Join_Now": "지금 참여",
      "Set_Status": "상태 설정",
      "Online": "온라인",
      "Offline": "오프라인",
      "Available": "사용 가능",
      "Away": "자리 비움",
      "Busy": "바쁨",
      "Out_of_Office": "부재중",
      "Notification_Preference": "알림 설정",
      "Languages": "언어",
      "Theme": "테마",
      "About_Us": "회사 소개",
      "Terms_Policy": "약관 및 정책",
      "Rate_App": "앱 평가하기",
      "Share_App": "앱 공유하기",
      "Help_Support": "도움말 및 지원",
      "Logout": "로그아웃",
      "Log_Out": "로그아웃",
      "Log_out_dialog_text": "정말 로그아웃 하시겠습니까?",
      "Start_meeting": "회의 시작",
      "Video_Connect": "영상 연결",
      "Use_Personal_ID": "개인 회의 ID 사용",
      "Join_meeting": "회의 참여",
      "Meeting_Id": "회의 ID",
      "Personal_Link": "개인 링크",
      "Join_with_personal_link": "개인 링크로 참여",
      "Join_with_meeting_ID": "회의 ID로 참여",
      "Enter_the_URL": "초대링크를 받으셨다면 URL을 입력하세요",
      "Add_Name": "이름 추가",
      "Join": "참여",
      "Invitation_link": "초대 링크를 받으셨다면, 링크를 다시 탭하여 회의에 참가하세요.",
      "Join_Option": "참여 옵션",
      "Connect_to_audio": "오디오 연결",
      "Don’t_Connect_to_audio": "오디오 연결 안 함",
      "Turn_on_my_video": "내 비디오 켜기",
      "Turn_off_my_video": "내 비디오 끄기",
      "Meeting_Name": "회의명",
      "Date": "날짜",
      "Time": "시간",
      "Time_Zone": "시간대",
      "Duration": "기간",
      "Security": "보안",
      "Passcode": "비밀번호",
      "Meeting_Options": "회의 옵션",
      "Host_video": "호스트 비디오",
      "Host_Audio": "호스트 오디오",
      "Edit": "편집",
      "Remove_Scheduled_Meeting": "예약된 회의 삭제",
      "Delete_scheduled_meeting_dialog_text": "예약된 회의를 정말 삭제하시겠습니까?",
      "Remove": "제거",
      "Delete": "삭제",
      "Passcode:": "비밀번호:",
      "Link:": "링크:",
      "Members": "참석자",
      "Show_More": "더 보기",
      "Invite_To_mail": "메일로 초대",
      "Invite": "초대",
      "Chat": "채팅",
      "Start": "시작",
      "Owner": "소유자",
      "Clear_All": "모두 지우기",
      "Write_your_message": "메시지를 입력하세요",
      "My_Profile": "내 프로필",
      "Display_Name": "표시 이름",
      "Phone_Number": "전화번호",
      "Location": "위치",
      "Job_Title": "직함",
      "Job_Titles": "직함",
      "Update_Password": "비밀번호 업데이트",
      "Not_Set": "미설정",
      "Update": "업데이트",
      "Enter your mobile number": "휴대전화 번호 입력",
      "Search_Location": "위치 검색",
      "Save": "저장",
      "Your_Designation": "직책",
      "Current_Password": "현재 비밀번호",
      "Enter_Old_Password": "이전 비밀번호 입력",
      "New_Password": "새 비밀번호",
      "Enter_New_Password": "새 비밀번호 입력",
      "Confirm_Password": "비밀번호 확인",
      "Confirm_New_Password": "새 비밀번호 확인",
      "Notification": "알림",
      "Notification_text": "알림을 켜거나 꺼서 설정에 맞게 조정할 수 있습니다.",
      "Light": "라이트",
      "Dark": "다크",
      "System_Default": "시스템 기본값",
    },
    "de": {
      "Start_Calling": "Anruf starten",
      "Skip": "Überspringen",
      "OnBoardingText1": "Trete Meetings überall und jederzeit bei.",
      "OnBoardingText2": "Melde dich an, um alle deine bevorstehenden Meetings zu sehen oder ein neues zu planen.",
      "OnBoardingText3": "Verbinde dich mit deinem Team",
      "Next": "Weiter",
      "Done": "Fertig",
      "Secure": "Sichere, intelligente und optimierte Gespräche",
      "Join_Meeting": "Meeting beitreten",
      "Sign_In": "Anmelden",
      "Sign_in": "Anmelden",
      "Don’t_account": "Noch keinen Account?",
      "Already_have_account": "Bereits einen Account?",
      "Sign_Up": "Registrieren",
      "Sign_up": "Registrieren",
      "Cancel": "Abbrechen",
      "Enter_your_email": "Gib deine E-Mail-Adresse ein",
      "Email": "E-Mail",
      "Password": "Passwort",
      "Required": "Erforderlich",
      "Forgot_password": "Passwort vergessen?",
      "Forgot_Password": "Passwort vergessen",
      "Other_Method": "Andere Anmeldemethode",
      "Other_sign_up_Method": "Andere Registrierungs-Methode",
      "Sign_in_Apple": "Mit Apple anmelden",
      "Sign_in_Google": "Mit Google anmelden",
      "Reset_password_text": "Um dein Passwort zurückzusetzen, gib bitte deine E-Mail-Adresse ein.",
      "Send": "Senden",
      "Forgot_Password_Dialog_Text":
          "Wir haben gerade eine E-Mail an user@example.com mit einem Link zum Zurücksetzen deines Passworts gesendet. Überprüfe dein Postfach und folge den Anweisungen in der E-Mail.",
      "OK": "OK",
      "Check_your_email": "Überprüfe deine E-Mails",
      "Verification_code_text": "Wir haben einen Bestätigungscode an user@example.com gesendet",
      "Code": "Code",
      "Verification_Code": "Bestätigungscode",
      "Didn’t_receive_verification_code": "Keinen Bestätigungscode erhalten?",
      "Resend": "Erneut senden",
      "Welcome_to_Weboxcam": "Willkommen bei Weboxcam",
      "Set_up_display_name_text": "Lass uns deinen Anzeigenamen in Weboxcam einrichten und ein Passwort erstellen.",
      "First_Name": "Vorname",
      "Last_Name": "Nachname",
      "Enter_First_Name": "Gib deinen Vornamen ein",
      "Enter_Last_Name": "Gib deinen Nachnamen ein",
      "Password_Requirements": "Passwortanforderungen*",
      "Must_Contain": "Muss enthalten",
      "At_least_number": "•  Mindestens 1 Zahl",
      "At_least_Uppercase": "•  Mindestens 1 Großbuchstabe",
      "At_least_lowercase": "•  Mindestens 1 Kleinbuchstabe",
      "At_least_8": "•  Mindestens 8 Zeichen",
      "Confirm_sign_up": "Registrierung bestätigen",
      "Get_Notified": "Benachrichtigungen erhalten",
      "Enable_notifications_text":
          "Aktiviere Benachrichtigungen, um Benachrichtigungen über Nachrichten, Meetings und Angebote zu erhalten. Diese kannst du in den App-Einstellungen verwalten.",
      "Enable_notifications": "Benachrichtigungen aktivieren",
      "Not_Now": "Jetzt nicht",
      "Never_Miss_a_meetings": "Verpasse nie ein Meeting",
      "Allow_Weboxcam_to_access_your": "Erlaube Weboxcam den Zugriff auf deinen Kalender, um Meetings einfacher zu planen und beizutreten.",
      "Continue": "Weiter",
      "You’re_ready": "Du bist bereit!",
      "Welcome_to_Weboxcam_for_Team_chat": "Willkommen bei Weboxcam – eine App für Team-Chat, Telefonate, Meetings und mehr.",
      "Go_To_Home": "Zur Startseite",
      "Meeting": "Meeting",
      "Schedule": "Planen",
      "Message": "Nachricht",
      "Setting": "Einstellungen",
      "Settings": "Einstellungen",
      "Calendar": "Kalender",
      "Start_New_Meeting": "Neues Meeting starten",
      "Schedule_Meeting": "Meeting planen",
      "No_Any_Meeting": "Keine Meetings vorhanden",
      "No_Any_Schedule": "Kein Zeitplan vorhanden",
      "No_Any_Message": "Keine Nachrichten vorhanden",
      "On_Going": "Laufend",
      "Meeting_ID": "Meeting-ID:",
      "Join_Now": "Jetzt beitreten",
      "Set_Status": "Status festlegen",
      "Online": "Online",
      "Offline": "Offline",
      "Available": "Verfügbar",
      "Away": "Abwesend",
      "Busy": "Beschäftigt",
      "Out_of_Office": "Außer Haus",
      "Notification_Preference": "Benachrichtigungseinstellungen",
      "Languages": "Sprachen",
      "Theme": "Design",
      "About_Us": "Über uns",
      "Terms_Policy": "Nutzungsbedingungen & Datenschutz",
      "Rate_App": "App bewerten",
      "Share_App": "App teilen",
      "Help_Support": "Hilfe & Support",
      "Logout": "Abmelden",
      "Log_Out": "Abmelden",
      "Log_out_dialog_text": "Möchtest du dich wirklich abmelden?",
      "Start_meeting": "Meeting starten",
      "Video_Connect": "Videoverbindung",
      "Use_Personal_ID": "Persönliche Meeting-ID verwenden",
      "Join_meeting": "Meeting beitreten",
      "Meeting_Id": "Meeting-ID",
      "Personal_Link": "Persönlicher Link",
      "Join_with_personal_link": "Mit persönlichem Link beitreten",
      "Join_with_meeting_ID": "Mit Meeting-ID beitreten",
      "Enter_the_URL": "Wenn du zu einem persönlichen Raum eingeladen wurdest, gib die URL ein",
      "Add_Name": "Name hinzufügen",
      "Join": "Beitreten",
      "Invitation_link": "Wenn du einen Einladungslink erhalten hast, tippe erneut auf den Link, um dem Meeting beizutreten.",
      "Join_Option": "Beitrittsoption",
      "Connect_to_audio": "Mit Audio verbinden",
      "Don’t_Connect_to_audio": "Nicht mit Audio verbinden",
      "Turn_on_my_video": "Mein Video aktivieren",
      "Turn_off_my_video": "Mein Video deaktivieren",
      "Meeting_Name": "Meeting-Name",
      "Date": "Datum",
      "Time": "Uhrzeit",
      "Time_Zone": "Zeitzone",
      "Duration": "Dauer",
      "Security": "Sicherheit",
      "Passcode": "Zugangscode",
      "Meeting_Options": "Meeting-Optionen",
      "Host_video": "Host-Video",
      "Host_Audio": "Host-Audio",
      "Edit": "Bearbeiten",
      "Remove_Scheduled_Meeting": "Geplantes Meeting entfernen",
      "Delete_scheduled_meeting_dialog_text": "Möchtest du das geplante Meeting wirklich löschen?",
      "Remove": "Entfernen",
      "Delete": "Löschen",
      "Passcode:": "Zugangscode:",
      "Link:": "Link:",
      "Members": "Mitglieder",
      "Show_More": "Mehr anzeigen",
      "Invite_To_mail": "Per E-Mail einladen",
      "Invite": "Einladen",
      "Chat": "Chat",
      "Start": "Starten",
      "Owner": "Besitzer",
      "Clear_All": "Alle löschen",
      "Write_your_message": "Schreibe deine Nachricht",
      "My_Profile": "Mein Profil",
      "Display_Name": "Anzeigename",
      "Phone_Number": "Telefonnummer",
      "Location": "Standort",
      "Job_Title": "Berufsbezeichnung",
      "Job_Titles": "Berufsbezeichnungen",
      "Update_Password": "Passwort aktualisieren",
      "Not_Set": "Nicht festgelegt",
      "Update": "Aktualisieren",
      "Enter your mobile number": "Gib deine Handynummer ein",
      "Search_Location": "Standort suchen",
      "Save": "Speichern",
      "Your_Designation": "Deine Bezeichnung",
      "Current_Password": "Aktuelles Passwort",
      "Enter_Old_Password": "Altes Passwort eingeben",
      "New_Password": "Neues Passwort",
      "Enter_New_Password": "Neues Passwort eingeben",
      "Confirm_Password": "Passwort bestätigen",
      "Confirm_New_Password": "Neues Passwort bestätigen",
      "Notification": "Benachrichtigung",
      "Notification_text": "Du kannst alle Benachrichtigungen ganz einfach nach deinen Vorlieben aktivieren oder deaktivieren.",
      "Light": "Hell",
      "Dark": "Dunkel",
      "System_Default": "Systemstandard",
    },
    "it": {
      "Start_Calling": "Avvia chiamata",
      "Skip": "Salta",
      "OnBoardingText1": "Partecipa a riunioni ovunque, in qualsiasi momento.",
      "OnBoardingText2": "Accedi per vedere tutte le tue riunioni future o per programmare una nuova.",
      "OnBoardingText3": "Connettiti con il tuo team",
      "Next": "Avanti",
      "Done": "Fatto",
      "Secure": "Conversazioni sicure, intelligenti e semplificate",
      "Join_Meeting": "Partecipa alla riunione",
      "Sign_In": "Accedi",
      "Sign_in": "Accedi",
      "Don’t_account": "Non hai un account? ",
      "Already_have_account": "Hai già un account? ",
      "Sign_Up": "Registrati",
      "Sign_up": "Registrati",
      "Cancel": "Annulla",
      "Enter_your_email": "Inserisci il tuo indirizzo email",
      "Email": "Email",
      "Password": "Password",
      "Required": "Obbligatorio",
      "Forgot_password": "Hai dimenticato la password?",
      "Forgot_Password": "Password dimenticata",
      "Other_Method": "Altri metodi di accesso",
      "Other_sign_up_Method": "Altri metodi di registrazione",
      "Sign_in_Apple": "Accedi con Apple",
      "Sign_in_Google": "Accedi con Google",
      "Reset_password_text": "Per reimpostare la password, inserisci il tuo indirizzo email.",
      "Send": "Invia",
      "Forgot_Password_Dialog_Text":
          "Abbiamo appena inviato un'email a user@exaple.com con un link per reimpostare la tua password. Controlla la tua casella di posta e segui le istruzioni.",
      "OK": "Ok",
      "Check_your_email": "Controlla la tua email",
      "Verification_code_text": "Abbiamo inviato un codice di verifica a user@example.com",
      "Code": "Codice",
      "Verification_Code": "Codice di verifica",
      "Didn’t_receive_verification_code": "Non hai ricevuto il codice di verifica?",
      "Resend": "Invia di nuovo",
      "Welcome_to_Weboxcam": "Benvenuto su Weboxcam",
      "Set_up_display_name_text": "Imposta il tuo nome visualizzato su Weboxcam e crea una password.",
      "First_Name": "Nome",
      "Last_Name": "Cognome",
      "Enter_First_Name": "Inserisci il nome",
      "Enter_Last_Name": "Inserisci il cognome",
      "Password_Requirements": "Requisiti della password*",
      "Must_Contain": "Deve contenere",
      "At_least_number": "• Almeno 1 numero",
      "At_least_Uppercase": "• Almeno 1 lettera maiuscola",
      "At_least_lowercase": "• Almeno 1 lettera minuscola",
      "At_least_8": "• Almeno 8 caratteri",
      "Confirm_sign_up": "Conferma registrazione",
      "Get_Notified": "Ricevi notifiche",
      "Enable_notifications_text":
          "Attiva le notifiche per ricevere avvisi su messaggi, riunioni e offerte. Puoi gestirle nelle impostazioni dell'app.",
      "Enable_notifications": "Attiva notifiche",
      "Not_Now": "Non ora",
      "Never_Miss_a_meetings": "Non perdere mai una riunione",
      "Allow_Weboxcam_to_access_your":
          "Consenti a Weboxcam di accedere al tuo calendario per programmare facilmente riunioni e parteciparvi direttamente dall'app.",
      "Continue": "Continua",
      "You’re_ready": "Sei pronto!",
      "Welcome_to_Weboxcam_for_Team_chat": "Benvenuto su Weboxcam, un'unica app per chat di squadra, telefono, riunioni e altro.",
      "Go_To_Home": "Vai alla home",
      "Meeting": "Riunione",
      "Schedule": "Pianifica",
      "Message": "Messaggio",
      "Setting": "Impostazioni",
      "Settings": "Impostazioni",
      "Calendar": "Calendario",
      "Start_New_Meeting": "Avvia nuova riunione",
      "Schedule_Meeting": "Programma riunione",
      "No_Any_Meeting": "Nessuna riunione",
      "No_Any_Schedule": "Nessuna pianificazione",
      "No_Any_Message": "Nessun messaggio",
      "On_Going": "In corso",
      "Meeting_ID": "ID Riunione:",
      "Join_Now": "Partecipa ora",
      "Set_Status": "Imposta stato",
      "Online": "Online",
      "Offline": "Offline",
      "Available": "Disponibile",
      "Away": "Assente",
      "Busy": "Occupato",
      "Out_of_Office": "Fuori ufficio",
      "Notification_Preference": "Preferenze di notifica",
      "Languages": "Lingue",
      "Theme": "Tema",
      "About_Us": "Chi siamo",
      "Terms_Policy": "Termini e Politica",
      "Rate_App": "Valuta l'app",
      "Share_App": "Condividi l'app",
      "Help_Support": "Aiuto e supporto",
      "Logout": "Disconnetti",
      "Log_Out": "Disconnetti",
      "Log_out_dialog_text": "Sei sicuro di voler uscire?",
      "Start_meeting": "Avvia una riunione",
      "Video_Connect": "Connessione video",
      "Use_Personal_ID": "Usa ID riunione personale",
      "Join_meeting": "Partecipa alla riunione",
      "Meeting_Id": "ID Riunione",
      "Personal_Link": "Link personale",
      "Join_with_personal_link": "Partecipa con un link personale",
      "Join_with_meeting_ID": "Partecipa con ID riunione",
      "Enter_the_URL": "Se sei stato invitato in una stanza personale, puoi inserire l'URL",
      "Add_Name": "Aggiungi nome",
      "Join": "Partecipa",
      "Invitation_link": "Se hai ricevuto un link di invito, toccalo di nuovo per partecipare alla riunione.",
      "Join_Option": "Opzione di partecipazione",
      "Connect_to_audio": "Connettiti all'audio",
      "Don’t_Connect_to_audio": "Non connetterti all'audio",
      "Turn_on_my_video": "Attiva il mio video",
      "Turn_off_my_video": "Disattiva il mio video",
      "Meeting_Name": "Nome riunione",
      "Date": "Data",
      "Time": "Ora",
      "Time_Zone": "Fuso orario",
      "Duration": "Durata",
      "Security": "Sicurezza",
      "Passcode": "Codice di accesso",
      "Meeting_Options": "Opzioni riunione",
      "Host_video": "Video dell'organizzatore",
      "Host_Audio": "Audio dell'organizzatore",
      "Edit": "Modifica",
      "Remove_Scheduled_Meeting": "Rimuovi riunione pianificata",
      "Delete_scheduled_meeting_dialog_text": "Sei sicuro di voler eliminare la riunione pianificata?",
      "Remove": "Rimuovi",
      "Delete": "Elimina",
      "Passcode:": "Codice di accesso:",
      "Link:": "Link:",
      "Members": "Membri",
      "Show_More": "Mostra di più",
      "Invite_To_mail": "Invita via mail",
      "Invite": "Invita",
      "Chat": "Chat",
      "Start": "Avvia",
      "Owner": "Proprietario",
      "Clear_All": "Cancella tutto",
      "Write_your_message": "Scrivi il tuo messaggio",
      "My_Profile": "Il mio profilo",
      "Display_Name": "Nome visualizzato",
      "Phone_Number": "Numero di telefono",
      "Location": "Posizione",
      "Job_Title": "Titolo professionale",
      "Job_Titles": "Titoli professionali",
      "Update_Password": "Aggiorna password",
      "Not_Set": "Non impostato",
      "Update": "Aggiorna",
      "Enter your mobile number": "Inserisci il tuo numero di cellulare",
      "Search_Location": "Cerca posizione",
      "Save": "Salva",
      "Your_Designation": "La tua qualifica",
      "Current_Password": "Password attuale",
      "Enter_Old_Password": "Inserisci la vecchia password",
      "New_Password": "Nuova password",
      "Enter_New_Password": "Inserisci la nuova password",
      "Confirm_Password": "Conferma password",
      "Confirm_New_Password": "Conferma la nuova password",
      "Notification": "Notifiche",
      "Notification_text": "Puoi attivare o disattivare tutte le notifiche secondo le tue preferenze.",
      "Light": "Chiaro",
      "Dark": "Scuro",
      "System_Default": "Predefinito di sistema",
    },
    "no": {
      "Start_Calling": "Start samtale",
      "Skip": "Hopp over",
      "OnBoardingText1": "Bli med i møter hvor som helst, når som helst.",
      "OnBoardingText2": "Logg inn for å se alle dine kommende møter eller planlegg et nytt møte.",
      "OnBoardingText3": "Koble med teamet ditt",
      "Next": "Neste",
      "Done": "Ferdig",
      "Secure": "Sikre, smarte og effektive samtaler",
      "Join_Meeting": "Bli med i møte",
      "Sign_In": "Logg Inn",
      "Sign_in": "Logg inn",
      "Don’t_account": "Har du ikke en konto? ",
      "Already_have_account": "Har du allerede en konto? ",
      "Sign_Up": "Registrer deg",
      "Sign_up": "Registrer deg",
      "Cancel": "Avbryt",
      "Enter_your_email": "Skriv inn e-postadressen din",
      "Email": "E-post",
      "Password": "Passord",
      "Required": "Påkrevd",
      "Forgot_password": "Glemt passord?",
      "Forgot_Password": "Glemt Passord",
      "Other_Method": "Andre påloggingsmetoder",
      "Other_sign_up_Method": "Andre registreringsmetoder",
      "Sign_in_Apple": "Logg inn med Apple",
      "Sign_in_Google": "Logg inn med Google",
      "Reset_password_text": "For å tilbakestille passordet ditt, vennligst skriv inn e-postadressen din.",
      "Send": "Send",
      "Forgot_Password_Dialog_Text":
          "Vi har sendt en e-post til user@exaple.com med en lenke for å tilbakestille passordet ditt. Sjekk innboksen din og følg instruksjonene i e-posten.",
      "OK": "Ok",
      "Check_your_email": "Sjekk e-posten din",
      "Verification_code_text": "Vi sendte en verifiseringskode til user@example.com",
      "Code": "Kode",
      "Verification_Code": "Verifiseringskode",
      "Didn’t_receive_verification_code": "Fikk du ikke verifiseringskode?",
      "Resend": "Send på nytt",
      "Welcome_to_Weboxcam": "Velkommen til Weboxcam",
      "Set_up_display_name_text": "La oss sette opp visningsnavnet ditt i Weboxcam og opprette et passord.",
      "First_Name": "Fornavn",
      "Last_Name": "Etternavn",
      "Enter_First_Name": "Skriv inn fornavn",
      "Enter_Last_Name": "Skriv inn etternavn",
      "Password_Requirements": "Passordkrav*",
      "Must_Contain": "Må inneholde",
      "At_least_number": "• Minst 1 tall",
      "At_least_Uppercase": "• Minst 1 stor bokstav",
      "At_least_lowercase": "• Minst 1 liten bokstav",
      "At_least_8": "• Minst 8 tegn",
      "Confirm_sign_up": "Bekreft registrering",
      "Get_Notified": "Få varsler",
      "Enable_notifications_text": "Aktiver varsler for å motta meldinger, møter og tilbud. Du kan administrere dette i appinnstillinger.",
      "Enable_notifications": "Aktiver varsler",
      "Not_Now": "Ikke nå",
      "Never_Miss_a_meetings": "Aldri gå glipp av møter",
      "Allow_Weboxcam_to_access_your":
          "Tillat Weboxcam å få tilgang til kalenderen din slik at du enkelt kan planlegge og delta i møter direkte fra appen.",
      "Continue": "Fortsett",
      "You’re_ready": "Du er klar!",
      "Welcome_to_Weboxcam_for_Team_chat": "Velkommen til Weboxcam – én app for teamchat, samtaler, møter og mer.",
      "Go_To_Home": "Gå til hjem",
      "Meeting": "Møte",
      "Schedule": "Planlegg",
      "Message": "Melding",
      "Setting": "Innstillinger",
      "Settings": "Innstillinger",
      "Calendar": "Kalender",
      "Start_New_Meeting": "Start nytt møte",
      "Schedule_Meeting": "Planlegg møte",
      "No_Any_Meeting": "Ingen møter",
      "No_Any_Schedule": "Ingen planlagte møter",
      "No_Any_Message": "Ingen meldinger",
      "On_Going": "Pågående",
      "Meeting_ID": "Møte-ID:",
      "Join_Now": "Bli med nå",
      "Set_Status": "Sett status",
      "Online": "Online",
      "Offline": "Offline",
      "Available": "Tilgjengelig",
      "Away": "Borte",
      "Busy": "Opptatt",
      "Out_of_Office": "Ikke på kontoret",
      "Notification_Preference": "Varslingspreferanser",
      "Languages": "Språk",
      "Theme": "Tema",
      "About_Us": "Om oss",
      "Terms_Policy": "Vilkår og personvern",
      "Rate_App": "Vurder appen",
      "Share_App": "Del appen",
      "Help_Support": "Hjelp og støtte",
      "Logout": "Logg ut",
      "Log_Out": "Logg ut",
      "Log_out_dialog_text": "Er du sikker på at du vil logge ut?",
      "Start_meeting": "Start et møte",
      "Video_Connect": "Video-tilkobling",
      "Use_Personal_ID": "Bruk personlig møte-ID",
      "Join_meeting": "Bli med i møte",
      "Meeting_Id": "Møte-ID",
      "Personal_Link": "Personlig lenke",
      "Join_with_personal_link": "Bli med med personlig lenke",
      "Join_with_meeting_ID": "Bli med med møte-ID",
      "Enter_the_URL": "Hvis du er invitert til et personlig rom, kan du skrive inn URL-en",
      "Add_Name": "Legg til navn",
      "Join": "Bli med",
      "Invitation_link": "Hvis du har mottatt en invitasjonslenke, trykk på den igjen for å bli med i møtet.",
      "Join_Option": "Alternativer for deltakelse",
      "Connect_to_audio": "Koble til lyd",
      "Don’t_Connect_to_audio": "Ikke koble til lyd",
      "Turn_on_my_video": "Slå på videoen min",
      "Turn_off_my_video": "Slå av videoen min",
      "Meeting_Name": "Møtenavn",
      "Date": "Dato",
      "Time": "Tid",
      "Time_Zone": "Tidssone",
      "Duration": "Varighet",
      "Security": "Sikkerhet",
      "Passcode": "Kode",
      "Meeting_Options": "Møtealternativer",
      "Host_video": "Vertens video",
      "Host_Audio": "Vertens lyd",
      "Edit": "Rediger",
      "Remove_Scheduled_Meeting": "Fjern planlagt møte",
      "Delete_scheduled_meeting_dialog_text": "Er du sikker på at du vil slette det planlagte møtet?",
      "Remove": "Fjern",
      "Delete": "Slett",
      "Passcode:": "Kode:",
      "Link:": "Lenke:",
      "Members": "Medlemmer",
      "Show_More": "Vis mer",
      "Invite_To_mail": "Inviter via e-post",
      "Invite": "Inviter",
      "Chat": "Chat",
      "Start": "Start",
      "Owner": "Eier",
      "Clear_All": "Fjern alt",
      "Write_your_message": "Skriv meldingen din",
      "My_Profile": "Min profil",
      "Display_Name": "Visningsnavn",
      "Phone_Number": "Telefonnummer",
      "Location": "Sted",
      "Job_Title": "Stillingstittel",
      "Job_Titles": "Stillingstitler",
      "Update_Password": "Oppdater passord",
      "Not_Set": "Ikke satt",
      "Update": "Oppdater",
      "Enter your mobile number": "Skriv inn mobilnummeret ditt",
      "Search_Location": "Søk etter sted",
      "Save": "Lagre",
      "Your_Designation": "Din stilling",
      "Current_Password": "Nåværende passord",
      "Enter_Old_Password": "Skriv inn gammelt passord",
      "New_Password": "Nytt passord",
      "Enter_New_Password": "Skriv inn nytt passord",
      "Confirm_Password": "Bekreft passord",
      "Confirm_New_Password": "Bekreft nytt passord",
      "Notification": "Varsling",
      "Notification_text": "Du kan enkelt aktivere eller deaktivere alle varsler etter dine preferanser.",
      "Light": "Lyst",
      "Dark": "Mørkt",
      "System_Default": "Systemstandard",
    },
    "pl": {
      "Start_Calling": "Rozpocznij rozmowę",
      "Skip": "Pomiń",
      "OnBoardingText1": "Dołącz do spotkania z dowolnego miejsca, o każdej porze.",
      "OnBoardingText2": "Zaloguj się, aby zobaczyć nadchodzące spotkania lub zaplanować nowe.",
      "OnBoardingText3": "Połącz się ze swoim zespołem",
      "Next": "Dalej",
      "Done": "Gotowe",
      "Secure": "Bezpieczne, inteligentne i usprawnione rozmowy",
      "Join_Meeting": "Dołącz do spotkania",
      "Sign_In": "Zaloguj się",
      "Sign_in": "Zaloguj się",
      "Don’t_account": "Nie masz konta? ",
      "Already_have_account": "Masz już konto? ",
      "Sign_Up": "Zarejestruj się",
      "Sign_up": "Zarejestruj się",
      "Cancel": "Anuluj",
      "Enter_your_email": "Wpisz swój adres e-mail",
      "Email": "E-mail",
      "Password": "Hasło",
      "Required": "Wymagane",
      "Forgot_password": "Zapomniałeś hasła?",
      "Forgot_Password": "Zapomniałeś hasła",
      "Other_Method": "Inna metoda logowania",
      "Other_sign_up_Method": "Inna metoda rejestracji",
      "Sign_in_Apple": "Zaloguj się przez Apple",
      "Sign_in_Google": "Zaloguj się przez Google",
      "Reset_password_text": "Aby zresetować hasło, wpisz swój adres e-mail.",
      "Send": "Wyślij",
      "Forgot_Password_Dialog_Text":
          "Wysłaliśmy wiadomość na adres user@example.com z linkiem do zresetowania hasła. Sprawdź skrzynkę odbiorczą i postępuj zgodnie z instrukcjami.",
      "OK": "Ok",
      "Check_your_email": "Sprawdź swoją skrzynkę mailową",
      "Verification_code_text": "Wysłaliśmy kod weryfikacyjny na adres user@example.com",
      "Code": "Kod",
      "Verification_Code": "Kod weryfikacyjny",
      "Didn’t_receive_verification_code": "Nie otrzymałeś kodu weryfikacyjnego?",
      "Resend": "Wyślij ponownie",
      "Welcome_to_Weboxcam": "Witamy w Weboxcam",
      "Set_up_display_name_text": "Ustaw wyświetlaną nazwę w Weboxcam i utwórz hasło.",
      "First_Name": "Imię",
      "Last_Name": "Nazwisko",
      "Enter_First_Name": "Wpisz imię",
      "Enter_Last_Name": "Wpisz nazwisko",
      "Password_Requirements": "Wymagania dotyczące hasła*",
      "Must_Contain": "Musi zawierać",
      "At_least_number": "•  Co najmniej 1 cyfrę",
      "At_least_Uppercase": "•  Co najmniej 1 wielką literę",
      "At_least_lowercase": "•  Co najmniej 1 małą literę",
      "At_least_8": "•  Co najmniej 8 znaków",
      "Confirm_sign_up": "Potwierdź rejestrację",
      "Get_Notified": "Otrzymuj powiadomienia",
      "Enable_notifications_text":
          "Włącz powiadomienia, aby otrzymywać alerty o wiadomościach, spotkaniach i ofertach. Możesz nimi zarządzać w ustawieniach aplikacji.",
      "Enable_notifications": "Włącz powiadomienia",
      "Not_Now": "Nie teraz",
      "Never_Miss_a_meetings": "Nigdy nie przegap spotkań",
      "Allow_Weboxcam_to_access_your":
          "Zezwól aplikacji Weboxcam na dostęp do Twojego kalendarza, aby łatwo planować i dołączać do spotkań bezpośrednio z aplikacji.",
      "Continue": "Kontynuuj",
      "You’re_ready": "Jesteś gotowy!",
      "Welcome_to_Weboxcam_for_Team_chat": "Witamy w Weboxcam – jednej aplikacji do czatu zespołowego, rozmów, spotkań i nie tylko.",
      "Go_To_Home": "Przejdź do strony głównej",
      "Meeting": "Spotkanie",
      "Schedule": "Harmonogram",
      "Message": "Wiadomość",
      "Setting": "Ustawienia",
      "Settings": "Ustawienia",
      "Calendar": "Kalendarz",
      "Start_New_Meeting": "Rozpocznij nowe spotkanie",
      "Schedule_Meeting": "Zaplanuj spotkanie",
      "No_Any_Meeting": "Brak spotkań",
      "No_Any_Schedule": "Brak harmonogramów",
      "No_Any_Message": "Brak wiadomości",
      "On_Going": "W trakcie",
      "Meeting_ID": "ID Spotkania:",
      "Join_Now": "Dołącz teraz",
      "Set_Status": "Ustaw status",
      "Online": "Online",
      "Offline": "Offline",
      "Available": "Dostępny",
      "Away": "Zaraz wracam",
      "Busy": "Zajęty",
      "Out_of_Office": "Poza biurem",
      "Notification_Preference": "Preferencje powiadomień",
      "Languages": "Języki",
      "Theme": "Motyw",
      "About_Us": "O nas",
      "Terms_Policy": "Regulamin i Polityka",
      "Rate_App": "Oceń aplikację",
      "Share_App": "Udostępnij aplikację",
      "Help_Support": "Pomoc i wsparcie",
      "Logout": "Wyloguj się",
      "Log_Out": "Wyloguj się",
      "Log_out_dialog_text": "Czy na pewno chcesz się wylogować?",
      "Start_meeting": "Rozpocznij spotkanie",
      "Video_Connect": "Połączenie wideo",
      "Use_Personal_ID": "Użyj osobistego ID spotkania",
      "Join_meeting": "Dołącz do spotkania",
      "Meeting_Id": "ID Spotkania",
      "Personal_Link": "Osobisty link",
      "Join_with_personal_link": "Dołącz za pomocą osobistego linku",
      "Join_with_meeting_ID": "Dołącz za pomocą ID spotkania",
      "Enter_the_URL": "Jeśli otrzymałeś zaproszenie do pokoju osobistego, wpisz tutaj URL",
      "Add_Name": "Dodaj imię",
      "Join": "Dołącz",
      "Invitation_link": "Jeśli otrzymałeś link z zaproszeniem, kliknij go ponownie, aby dołączyć do spotkania.",
      "Join_Option": "Opcja dołączenia",
      "Connect_to_audio": "Połącz z dźwiękiem",
      "Don’t_Connect_to_audio": "Nie łącz z dźwiękiem",
      "Turn_on_my_video": "Włącz mój wideo",
      "Turn_off_my_video": "Wyłącz mój wideo",
      "Meeting_Name": "Nazwa spotkania",
      "Date": "Data",
      "Time": "Czas",
      "Time_Zone": "Strefa czasowa",
      "Duration": "Czas trwania",
      "Security": "Bezpieczeństwo",
      "Passcode": "Kod dostępu",
      "Meeting_Options": "Opcje spotkania",
      "Host_video": "Wideo gospodarza",
      "Host_Audio": "Audio gospodarza",
      "Edit": "Edytuj",
      "Remove_Scheduled_Meeting": "Usuń zaplanowane spotkanie",
      "Delete_scheduled_meeting_dialog_text": "Czy na pewno chcesz usunąć zaplanowane spotkanie?",
      "Remove": "Usuń",
      "Delete": "Usuń",
      "Passcode:": "Kod dostępu:",
      "Link:": "Link:",
      "Members": "Uczestnicy",
      "Show_More": "Pokaż więcej",
      "Invite_To_mail": "Zaproś przez e-mail",
      "Invite": "Zaproś",
      "Chat": "Czat",
      "Start": "Start",
      "Owner": "Właściciel",
      "Clear_All": "Wyczyść wszystko",
      "Write_your_message": "Napisz wiadomość",
      "My_Profile": "Mój profil",
      "Display_Name": "Wyświetlana nazwa",
      "Phone_Number": "Numer telefonu",
      "Location": "Lokalizacja",
      "Job_Title": "Stanowisko",
      "Job_Titles": "Stanowiska",
      "Update_Password": "Zaktualizuj hasło",
      "Not_Set": "Nie ustawiono",
      "Update": "Aktualizuj",
      "Enter your mobile number": "Wpisz swój numer telefonu",
      "Search_Location": "Szukaj lokalizacji",
      "Save": "Zapisz",
      "Your_Designation": "Twoje stanowisko",
      "Current_Password": "Obecne hasło",
      "Enter_Old_Password": "Wpisz stare hasło",
      "New_Password": "Nowe hasło",
      "Enter_New_Password": "Wpisz nowe hasło",
      "Confirm_Password": "Potwierdź hasło",
      "Confirm_New_Password": "Potwierdź nowe hasło",
      "Notification": "Powiadomienie",
      "Notification_text": "Możesz łatwo włączyć lub wyłączyć wszystkie powiadomienia według własnych preferencji.",
      "Light": "Jasny",
      "Dark": "Ciemny",
      "System_Default": "Domyślne systemowe",
    },
    "ja": {
      "Start_Calling": "通話を開始",
      "Skip": "スキップ",
      "OnBoardingText1": "いつでもどこでも会議に参加できます。",
      "OnBoardingText2": "すべての今後の会議を表示または新しい会議をスケジュールするには、サインインしてください。",
      "OnBoardingText3": "チームとつながろう",
      "Next": "次へ",
      "Done": "完了",
      "Secure": "安全でスマート、効率的な会話",
      "Join_Meeting": "会議に参加",
      "Sign_In": "サインイン",
      "Sign_in": "サインイン",
      "Don’t_account": "アカウントをお持ちでない場合は ",
      "Already_have_account": "すでにアカウントをお持ちですか？ ",
      "Sign_Up": "サインアップ",
      "Sign_up": "サインアップ",
      "Cancel": "キャンセル",
      "Enter_your_email": "メールアドレスを入力してください",
      "Email": "メールアドレス",
      "Password": "パスワード",
      "Required": "必須",
      "Forgot_password": "パスワードをお忘れですか？",
      "Forgot_Password": "パスワードをお忘れですか",
      "Other_Method": "他のサインイン方法",
      "Other_sign_up_Method": "他のサインアップ方法",
      "Sign_in_Apple": "Appleでサインイン",
      "Sign_in_Google": "Googleでサインイン",
      "Reset_password_text": "パスワードをリセットするには、メールアドレスを入力してください。",
      "Send": "送信",
      "Forgot_Password_Dialog_Text": "user@example.com にパスワードリセットリンクを送信しました。メールを確認し、手順に従ってください。",
      "OK": "OK",
      "Check_your_email": "メールを確認してください",
      "Verification_code_text": "user@example.com に認証コードを送信しました",
      "Code": "コード",
      "Verification_Code": "認証コード",
      "Didn’t_receive_verification_code": "認証コードを受け取っていませんか？",
      "Resend": "再送信",
      "Welcome_to_Weboxcam": "Weboxcamへようこそ",
      "Set_up_display_name_text": "Weboxcamで表示名とパスワードを設定しましょう。",
      "First_Name": "名",
      "Last_Name": "姓",
      "Enter_First_Name": "名を入力",
      "Enter_Last_Name": "姓を入力",
      "Password_Requirements": "パスワード要件*",
      "Must_Contain": "以下を含める必要があります",
      "At_least_number": "•  少なくとも1つの数字",
      "At_least_Uppercase": "•  少なくとも1つの大文字",
      "At_least_lowercase": "•  少なくとも1つの小文字",
      "At_least_8": "•  8文字以上",
      "Confirm_sign_up": "サインアップを確認",
      "Get_Notified": "通知を受け取る",
      "Enable_notifications_text": "メッセージ、会議、オファーの通知を受け取るには通知を有効にしてください。アプリの設定で管理できます。",
      "Enable_notifications": "通知を有効にする",
      "Not_Now": "今はしない",
      "Never_Miss_a_meetings": "会議を見逃さない",
      "Allow_Weboxcam_to_access_your": "カレンダーにアクセスを許可すると、簡単に会議をスケジュールし、アプリから直接参加できます。",
      "Continue": "続行",
      "You’re_ready": "準備完了です！",
      "Welcome_to_Weboxcam_for_Team_chat": "Weboxcamへようこそ。チームチャット、電話、会議などすべてを1つのアプリで。",
      "Go_To_Home": "ホームへ移動",
      "Meeting": "会議",
      "Schedule": "スケジュール",
      "Message": "メッセージ",
      "Setting": "設定",
      "Settings": "設定",
      "Calendar": "カレンダー",
      "Start_New_Meeting": "新しい会議を開始",
      "Schedule_Meeting": "会議をスケジュール",
      "No_Any_Meeting": "会議はありません",
      "No_Any_Schedule": "スケジュールはありません",
      "No_Any_Message": "メッセージはありません",
      "On_Going": "進行中",
      "Meeting_ID": "会議ID：",
      "Join_Now": "今すぐ参加",
      "Set_Status": "ステータスを設定",
      "Online": "オンライン",
      "Offline": "オフライン",
      "Available": "利用可能",
      "Away": "離席中",
      "Busy": "取り込み中",
      "Out_of_Office": "外出中",
      "Notification_Preference": "通知設定",
      "Languages": "言語",
      "Theme": "テーマ",
      "About_Us": "当社について",
      "Terms_Policy": "利用規約とポリシー",
      "Rate_App": "アプリを評価",
      "Share_App": "アプリを共有",
      "Help_Support": "ヘルプとサポート",
      "Logout": "ログアウト",
      "Log_Out": "ログアウト",
      "Log_out_dialog_text": "本当にログアウトしますか？",
      "Start_meeting": "会議を開始",
      "Video_Connect": "ビデオ接続",
      "Use_Personal_ID": "個人会議IDを使用",
      "Join_meeting": "会議に参加",
      "Meeting_Id": "会議ID",
      "Personal_Link": "個人リンク",
      "Join_with_personal_link": "個人リンクで参加",
      "Join_with_meeting_ID": "会議IDで参加",
      "Enter_the_URL": "個人ルームに招待された場合は、URLを入力してください",
      "Add_Name": "名前を追加",
      "Join": "参加",
      "Invitation_link": "招待リンクを受け取った場合は、再度リンクをタップして会議に参加してください。",
      "Join_Option": "参加オプション",
      "Connect_to_audio": "音声に接続",
      "Don’t_Connect_to_audio": "音声に接続しない",
      "Turn_on_my_video": "ビデオをオンにする",
      "Turn_off_my_video": "ビデオをオフにする",
      "Meeting_Name": "会議名",
      "Date": "日付",
      "Time": "時間",
      "Time_Zone": "タイムゾーン",
      "Duration": "時間",
      "Security": "セキュリティ",
      "Passcode": "パスコード",
      "Meeting_Options": "会議オプション",
      "Host_video": "ホストのビデオ",
      "Host_Audio": "ホストの音声",
      "Edit": "編集",
      "Remove_Scheduled_Meeting": "スケジュールされた会議を削除",
      "Delete_scheduled_meeting_dialog_text": "スケジュールされた会議を削除してもよろしいですか？",
      "Remove": "削除",
      "Delete": "削除",
      "Passcode:": "パスコード：",
      "Link:": "リンク：",
      "Members": "メンバー",
      "Show_More": "さらに表示",
      "Invite_To_mail": "メールで招待",
      "Invite": "招待",
      "Chat": "チャット",
      "Start": "開始",
      "Owner": "オーナー",
      "Clear_All": "すべてクリア",
      "Write_your_message": "メッセージを入力してください",
      "My_Profile": "マイプロフィール",
      "Display_Name": "表示名",
      "Phone_Number": "電話番号",
      "Location": "場所",
      "Job_Title": "職種",
      "Job_Titles": "職種",
      "Update_Password": "パスワードを更新",
      "Not_Set": "未設定",
      "Update": "更新",
      "Enter your mobile number": "携帯電話番号を入力してください",
      "Search_Location": "場所を検索",
      "Save": "保存",
      "Your_Designation": "あなたの肩書き",
      "Current_Password": "現在のパスワード",
      "Enter_Old_Password": "古いパスワードを入力",
      "New_Password": "新しいパスワード",
      "Enter_New_Password": "新しいパスワードを入力",
      "Confirm_Password": "パスワードの確認",
      "Confirm_New_Password": "新しいパスワードを確認",
      "Notification": "通知",
      "Notification_text": "好みに合わせてすべての通知を有効または無効にできます。",
      "Light": "ライト",
      "Dark": "ダーク",
      "System_Default": "システムのデフォルト",
    },
  };
}
